### ISSUE TITLE
 Detect paper sheet on an image

### ISSUE THREAD

**Issue by maxiimou** [ograndedjogo/tab-translator#1]
Taking an image as argument, we should detect a paper sheet location

**Comment by maxiimou** [comment]
# Interessant topics:
 - [Square detection](http://stackoverflow.com/questions/8667818/opencv-c-obj-c-detecting-a-sheet-of-paper-square-detection)
 - [perspective management](http://stackoverflow.com/questions/7838487/executing-cvwarpperspective-for-a-fake-deskewing-on-a-set-of-cvpoint)

**Comment by Lamaw** [comment]
[Here](http://images.google.fr/imgres?imgurl=http%3A%2F%2Fimg.cdandlp.com%2F2014%2F10%2FimgL%2F117183542.jpg&imgrefurl=http%3A%2F%2Fwww.cdandlp.com%2Fmouloudji%2Fpartition-vintage-sheet-music-mouloudji-%3A-le-heros%2Fpartition%2Fr117183542%2F&h=600&w=600&tbnid=SBb4-WlCh1xf8M%3A&docid=PSD7RGHZyjpshM&ei=cSdjVtmbK8Wza6mpvJAD&tbm=isch&client=ubuntu&iact=rc&uact=3&dur=663&page=1&start=0&ndsp=51&ved=0ahUKEwiZmPvEp8XJAhXF2RoKHakUDzIQrQMIaTAX) is a picture of partition sheet, to use for example :
