### ISSUE TITLE
Define a map for notes representation

### ISSUE THREAD

**Issue by Lamaw** [ograndedjogo/tab-translator#4]
Each note from musical theory is unique, but it may have many different representation.
The 440 Hz note (A4) has a different representation whether it's printed on key of G stave, or on a key of F stave, for example. It also has many representation possible on a tab where it can be the 5th sting played open, the fourth one at the 7th fret, the 3rd one at 2nd fret, etc...

A map recording all representations for every note must be generated in order to be used in music sheet-generation algorithms

**Comment by maxiimou** [comment]
Might be interesting to see what already exists in data music representation.
I found this [article](http://www.music-software-development.com/music-data-structures.html)

**Comment by Lamaw** [comment]
##### LylyPond is a tool that seems quite adapted for music sheet generation:

>"LilyPond is a music engraving program, devoted to producing the highest-quality sheet music 
> possible. It brings the aesthetics of traditionally engraved music to computer printouts." 

We can start Lilypond on a command shell, it reads plain text '.ly' files and produce music sheets.


##### More info about LylyPond and python
http://www.python-course.eu/python_scores.php
